//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Particle.h
//  @ Date : 12/4/2011
//  @ Author : 
//
//


#if !defined(_PARTICLE_H)
#define _PARTICLE_H


class Particle {
public:
	int postion[3]: double;
	int velocity[3]:double;
	int mass:double;
	int charge:double;
	int hydrophobe:double;
	int double angularMomentum;
};

#endif  //_PARTICLE_H
