//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : ChainParticles.h
//  @ Date : 12/4/2011
//  @ Author : 
//
//


#if !defined(_CHAINPARTICLES_H)
#define _CHAINPARTICLES_H


class ChainParticles {
public:
	int arrayParticles: Particle;
	void potentialEnergy();
	void girationRadio:double();
};

#endif  //_CHAINPARTICLES_H
