//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : ChainParticles.cpp
//  @ Date : 12/4/2011
//  @ Author : 
//
//


#include "ChainParticles.h"

void ChainParticles::potentialEnergy() {

}

void ChainParticles::girationRadio:double() {

}

